In [1]:
from numpy import *

In [2]:
#100 movies and 584 users are taken
num_movies = 100
num_users = 584

In [3]:
#randomly ratings are given to each movies by each users from 0 to 10
ratings = random.randint(11, size = (num_movies, num_users))
ratings.shape
ratings

array([[ 0,  9,  0, ...,  3,  1, 10],
       [ 1,  5,  5, ...,  1,  7,  6],
       [ 5,  4,  8, ...,  5,  3,  8],
       ...,
       [10, 10,  7, ...,  7,  0,  2],
       [ 8,  6,  2, ...,  5,  8,  2],
       [ 1,  5,  9, ...,  4,  7,  5]])

In [4]:
#matrix to check if any user has given rating or not
did_rate = (ratings != 0)
did_rate.shape
did_rate

array([[False,  True, False, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [5]:
#A column matrix for a new user to whom movies will be recommended and he has rated only 3 movies
my_ratings = zeros((num_movies, 1))
print (my_ratings)
print (my_ratings[9]) 
my_ratings[0] = 8
my_ratings[4] = 7
my_ratings[7] = 3
print (my_ratings)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0.]
[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [6]:
#appending the new user's column matrix to the original rating matrix
ratings = append(my_ratings, ratings, axis = 1)
ratings.shape
print (ratings)

[[ 8.  0.  9. ...  3.  1. 10.]
 [ 0.  1.  5. ...  1.  7.  6.]
 [ 0.  5.  4. ...  5.  3.  8.]
 ...
 [ 0. 10. 10. ...  7.  0.  2.]
 [ 0.  8.  6. ...  5.  8.  2.]
 [ 0.  1.  5. ...  4.  7.  5.]]


In [7]:
#updating the did_rate matrix whether a user has given rating or not
did_rate = append(((my_ratings != 0) * 1), did_rate, axis = 1)
did_rate.shape
did_rate

array([[1, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [8]:

def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = where(did_rate[i] == 1)[0]
        idx
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean

In [9]:
#normalize the ratings matrix by normalize_ratings function
ratings, ratings_mean = normalize_ratings(ratings, did_rate)
ratings

array([[ 2.40186916,  0.        ,  3.40186916, ..., -2.59813084,
        -4.59813084,  4.40186916],
       [ 0.        , -4.43761996, -0.43761996, ..., -4.43761996,
         1.56238004,  0.56238004],
       [ 0.        , -0.52190476, -1.52190476, ..., -0.52190476,
        -2.52190476,  2.47809524],
       ...,
       [ 0.        ,  4.45419847,  4.45419847, ...,  1.45419847,
         0.        , -3.54580153],
       [ 0.        ,  2.49227799,  0.49227799, ..., -0.50772201,
         2.49227799, -3.50772201],
       [ 0.        , -4.57007576, -0.57007576, ..., -1.57007576,
         1.42992424, -0.57007576]])

In [10]:
#number of features of a movie is assumed as 6
num_users = ratings.shape[1]
num_features = 6

In [11]:
#randomly generated movie features matrix for each movie and user preference matrix for each user
movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

In [12]:
movie_features

array([[ 0.06887898,  0.31470486, -0.56297419, -0.3070383 ,  1.16700392,
         0.62052813],
       [-0.62452997,  1.16746369,  0.47651425,  1.86454538, -0.66007339,
        -0.69486392],
       [ 1.69149298,  0.04729778,  0.53585737,  0.35347399,  1.61761348,
         0.13237811],
       [ 1.83725886,  0.53929239,  0.09236759, -0.71378356, -0.84911759,
         0.69289686],
       [-0.73731777, -1.03740474, -1.50796667,  0.53060225,  1.50822354,
         0.14352174],
       [ 0.28547471, -0.79226226, -0.24101345,  0.7045968 , -0.94074418,
         1.92391075],
       [ 0.45917553, -0.44138095, -0.10526261,  0.25160751,  1.76180213,
         0.36081   ],
       [-0.89035654,  1.07127636, -0.53534186,  0.1434846 , -0.25730751,
         2.83711767],
       [ 0.25067136, -2.3447683 , -0.89601487,  2.48987323, -0.34182512,
        -0.72300573],
       [-1.29821825, -0.08277028, -0.15658669,  0.45681457,  0.56146174,
        -0.26942629],
       [-0.30474936,  1.39119207,  0.23113007,  0.

In [13]:
user_prefs

array([[ 0.4337359 , -0.32391946,  0.73052722, -0.9582485 ,  0.59015912,
        -1.21150632],
       [-0.22832885, -0.20972275, -1.29513802, -0.9232175 ,  0.58505727,
        -0.47906023],
       [-0.75249077,  1.06432989, -1.19601164,  0.38739054, -1.38934515,
         0.10789299],
       ...,
       [ 0.55516958, -0.08666472,  1.81994157,  1.18267244,  1.27267477,
        -0.08780684],
       [ 1.376645  , -0.35143865,  1.23229254,  0.88940907,  0.64425969,
        -1.37727016],
       [-1.12365137, -0.24546397,  0.20595293,  0.04757815, -0.07283739,
        -1.18757923]])

In [14]:
initial_X_and_theta
#"initial_X_and_theta.shape

array([ 0.06887898, -0.62452997,  1.69149298, ..., -0.08780684,
       -1.37727016, -1.18757923])

In [15]:
movie_features.T.flatten().shape

(600,)

In [16]:
user_prefs.T.flatten().shape

(3510,)

In [17]:
initial_X_and_theta

array([ 0.06887898, -0.62452997,  1.69149298, ..., -0.08780684,
       -1.37727016, -1.18757923])

In [18]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
	# Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
	# --------------------------------------------------------------------------------------------------------------
	# Get the first 30 (10 * 3) rows in the 48 X 1 column vector
	first_30 = X_and_theta[:num_movies * num_features]
	# Reshape this column vector into a 10 X 3 matrix
	X = first_30.reshape((num_features, num_movies)).transpose()
	# Get the rest of the 18 the numbers, after the first 30
	last_18 = X_and_theta[num_movies * num_features:]
	# Reshape this column vector into a 6 X 3 matrix
	theta = last_18.reshape(num_features, num_users ).transpose()
	return X, theta


In [19]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply by did_rate because we only want to consider observations for which a rating was given
	difference = X.dot( theta.T ) * did_rate - ratings
	X_grad = difference.dot( theta ) + reg_param * X
	theta_grad = difference.T.dot( X ) + reg_param * theta
	
	# wrap the gradients back into a column vector 
	return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [20]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
	cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
	# '**' means an element-wise power
	regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
	return cost + regularization

In [21]:
from scipy import optimize

In [22]:
reg_param = 30

In [23]:
minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta, 								args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), 								maxiter=100, disp=True, full_output=True ) 
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]
movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)

         Current function value: 208559.819319
         Iterations: 100
         Function evaluations: 152
         Gradient evaluations: 152


In [24]:
movie_features

array([[ 1.33015753e+00, -2.87900765e-01,  8.14302335e-01,
         9.27670777e-02,  4.54038306e-01,  9.61248095e-01],
       [ 8.01252585e-01, -1.11344152e+00, -9.35337803e-01,
         3.58340743e-01,  7.18478307e-02,  6.13581926e-01],
       [-1.04565034e+00,  3.31680233e-02, -5.01983312e-01,
        -9.15519561e-01, -1.82523291e-01, -1.50536461e+00],
       [ 2.95164145e-01, -8.32591513e-01, -2.08105506e-01,
        -1.47020698e-01, -8.65455611e-01,  1.44377153e+00],
       [-6.79009127e-01,  2.29610762e-01, -1.38809686e+00,
        -3.68450288e-02, -6.45893179e-01,  1.10048084e+00],
       [-5.85227068e-01,  4.17511501e-01,  9.51549873e-02,
         9.38284355e-01, -3.36449159e-01,  3.46356053e-01],
       [ 7.34555230e-01, -1.10104050e+00, -3.66184462e-01,
        -4.33453121e-01,  1.10706959e+00,  3.45956868e-01],
       [ 2.51033723e-01,  8.27386579e-01, -3.03856239e-01,
         3.11863626e-01, -4.58044017e-01,  7.40797579e-01],
       [-1.24884335e+00, -1.19913527e+00, -2.264

In [25]:
#after 152 times iteration the final user preference matrix
user_prefs

array([[ 0.04043735, -0.07821493,  0.00994484, -0.02140871,  0.03680506,
         0.06965005],
       [ 0.75898114, -0.14062164,  0.17528107,  0.1506119 , -0.17767455,
        -0.13881118],
       [ 0.37146549,  0.37548412,  0.21101576, -0.92110443, -0.0081971 ,
         0.13934951],
       ...,
       [-0.2318492 ,  0.52511711,  0.03254082, -0.22050021, -0.52699952,
        -0.15672213],
       [-0.78918071,  0.43973348,  0.12567013,  0.53034172,  0.06741624,
        -0.3250283 ],
       [-0.3795683 , -0.45942041, -0.50149433,  0.0443749 ,  0.11685283,
        -0.11934819]])

In [31]:
#all predicted ratings for each movies by each users
all_predictions = movie_features.dot( user_prefs.T )

In [32]:
all_predictions

array([[ 0.16608014,  0.99265013,  0.60261557, ..., -0.8434615 ,
        -1.30662582, -0.83853718],
       [ 0.14789526,  0.55679538, -0.56296879, ..., -1.01393348,
        -1.24403935,  0.62754135],
       [-0.14183611, -0.78277816,  0.15311812, ...,  0.77750124,
         0.76815071,  0.75110753],
       ...,
       [-0.02038205,  0.30187766,  0.33732255, ..., -0.02464968,
        -0.53964614,  0.31677859],
       [-0.06852001,  0.55723978, -0.37793209, ..., -0.26171624,
         0.4714143 , -0.43531111],
       [ 0.02942923, -0.00923307, -0.07566749, ..., -0.28931226,
        -0.23519526,  0.02633085]])

In [33]:
#predicted ratings matrix for the new user.The movies having higher rating will be recommended to the user
predictions_for_me = all_predictions[:, 1:2] + ratings_mean

In [29]:
predictions_for_me

array([[6.59078097],
       [5.99441535],
       [4.7391266 ],
       [5.83053916],
       [4.5175599 ],
       [5.10588013],
       [5.79720213],
       [5.60221254],
       [4.32242109],
       [5.69928202],
       [5.7710694 ],
       [5.09142929],
       [4.8686972 ],
       [5.00302208],
       [4.70237406],
       [4.73445142],
       [5.01708722],
       [4.88987769],
       [5.39094928],
       [5.52776065],
       [4.84016824],
       [6.18965587],
       [5.00519966],
       [5.74493294],
       [4.98855667],
       [4.36750121],
       [7.36160818],
       [5.25139118],
       [5.89336509],
       [4.75800345],
       [6.45178028],
       [7.06787617],
       [4.6601047 ],
       [5.74199037],
       [5.70740281],
       [5.86090931],
       [5.23730821],
       [6.72412287],
       [5.53697263],
       [5.32508553],
       [6.74659338],
       [4.38831377],
       [6.02523519],
       [5.27182984],
       [6.53270306],
       [5.34450326],
       [6.269501  ],
       [5.726

In [34]:
my_ratings

array([[8.],
       [0.],
       [0.],
       [0.],
       [7.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],