In [1]:
from numpy import *

In [2]:
num_movies = 10
num_users = 5

In [3]:
ratings = random.randint(11, size = (num_movies, num_users))
ratings.shape
ratings

array([[ 8,  0,  2,  8,  0],
       [ 8, 10,  1,  5,  9],
       [ 8,  0, 10, 10,  6],
       [ 7,  5, 10,  4,  7],
       [ 0,  0,  6,  8,  2],
       [ 5,  2,  4,  4,  8],
       [ 7,  0,  6,  1,  1],
       [ 2,  6,  8,  1,  8],
       [ 8,  3,  7,  5,  7],
       [ 5,  0,  9,  1,  3]])

In [4]:
did_rate = (ratings != 0)
did_rate.shape
did_rate

array([[ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [5]:
my_ratings = zeros((num_movies, 1))
print (my_ratings)
print (my_ratings[9]) 
my_ratings[0] = 8
my_ratings[4] = 7
my_ratings[7] = 3
print (my_ratings)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0.]
[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [6]:
ratings = append(my_ratings, ratings, axis = 1)
ratings.shape
print (ratings)

[[ 8.  8.  0.  2.  8.  0.]
 [ 0.  8. 10.  1.  5.  9.]
 [ 0.  8.  0. 10. 10.  6.]
 [ 0.  7.  5. 10.  4.  7.]
 [ 7.  0.  0.  6.  8.  2.]
 [ 0.  5.  2.  4.  4.  8.]
 [ 0.  7.  0.  6.  1.  1.]
 [ 3.  2.  6.  8.  1.  8.]
 [ 0.  8.  3.  7.  5.  7.]
 [ 0.  5.  0.  9.  1.  3.]]


In [7]:
did_rate = append(((my_ratings != 0) * 1), did_rate, axis = 1)
did_rate.shape
did_rate

array([[1, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1]])

In [8]:

def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = where(did_rate[i] == 1)[0]
        idx
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean

In [9]:
ratings, ratings_mean = normalize_ratings(ratings, did_rate)
ratings

array([[ 1.5       ,  1.5       ,  0.        , -4.5       ,  1.5       ,
         0.        ],
       [ 0.        ,  1.4       ,  3.4       , -5.6       , -1.6       ,
         2.4       ],
       [ 0.        , -0.5       ,  0.        ,  1.5       ,  1.5       ,
        -2.5       ],
       [ 0.        ,  0.4       , -1.6       ,  3.4       , -2.6       ,
         0.4       ],
       [ 1.25      ,  0.        ,  0.        ,  0.25      ,  2.25      ,
        -3.75      ],
       [ 0.        ,  0.4       , -2.6       , -0.6       , -0.6       ,
         3.4       ],
       [ 0.        ,  3.25      ,  0.        ,  2.25      , -2.75      ,
        -2.75      ],
       [-1.66666667, -2.66666667,  1.33333333,  3.33333333, -3.66666667,
         3.33333333],
       [ 0.        ,  2.        , -3.        ,  1.        , -1.        ,
         1.        ],
       [ 0.        ,  0.5       ,  0.        ,  4.5       , -3.5       ,
        -1.5       ]])

In [10]:
num_users = ratings.shape[1]
num_features = 3

In [11]:
movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

In [12]:
movie_features

array([[-0.08712863, -0.89259375, -0.846546  ],
       [-0.53908156, -0.93183985,  0.15377259],
       [ 0.43399413,  0.11041334, -1.03663527],
       [-1.41146649,  0.50639712, -0.71902043],
       [-0.98139082,  0.5269427 ,  0.30918469],
       [-0.06398669,  1.05281112, -0.59770827],
       [ 0.94726703, -0.58178892,  0.33811961],
       [ 0.43729525, -0.02050452,  1.11764318],
       [ 0.81490481, -0.39326389, -1.50948505],
       [ 1.35156295, -1.03631201, -1.02328292]])

In [13]:
user_prefs

array([[ 0.57009446,  1.91083631,  1.11115829],
       [ 0.60034788, -1.73575556,  0.66343815],
       [-1.76655914,  1.04966199, -0.74842914],
       [ 1.42463001, -0.35310613,  0.50370552],
       [-0.02084461,  0.0596257 , -0.58103699],
       [ 0.30971683, -1.59024748, -0.0430107 ]])

In [14]:
initial_X_and_theta
#"initial_X_and_theta.shape

array([-0.08712863, -0.53908156,  0.43399413, -1.41146649, -0.98139082,
       -0.06398669,  0.94726703,  0.43729525,  0.81490481,  1.35156295,
       -0.89259375, -0.93183985,  0.11041334,  0.50639712,  0.5269427 ,
        1.05281112, -0.58178892, -0.02050452, -0.39326389, -1.03631201,
       -0.846546  ,  0.15377259, -1.03663527, -0.71902043,  0.30918469,
       -0.59770827,  0.33811961,  1.11764318, -1.50948505, -1.02328292,
        0.57009446,  0.60034788, -1.76655914,  1.42463001, -0.02084461,
        0.30971683,  1.91083631, -1.73575556,  1.04966199, -0.35310613,
        0.0596257 , -1.59024748,  1.11115829,  0.66343815, -0.74842914,
        0.50370552, -0.58103699, -0.0430107 ])

In [15]:
movie_features.T.flatten().shape

(30,)

In [16]:
user_prefs.T.flatten().shape

(18,)

In [17]:
initial_X_and_theta

array([-0.08712863, -0.53908156,  0.43399413, -1.41146649, -0.98139082,
       -0.06398669,  0.94726703,  0.43729525,  0.81490481,  1.35156295,
       -0.89259375, -0.93183985,  0.11041334,  0.50639712,  0.5269427 ,
        1.05281112, -0.58178892, -0.02050452, -0.39326389, -1.03631201,
       -0.846546  ,  0.15377259, -1.03663527, -0.71902043,  0.30918469,
       -0.59770827,  0.33811961,  1.11764318, -1.50948505, -1.02328292,
        0.57009446,  0.60034788, -1.76655914,  1.42463001, -0.02084461,
        0.30971683,  1.91083631, -1.73575556,  1.04966199, -0.35310613,
        0.0596257 , -1.59024748,  1.11115829,  0.66343815, -0.74842914,
        0.50370552, -0.58103699, -0.0430107 ])

In [18]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
	# Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
	# --------------------------------------------------------------------------------------------------------------
	# Get the first 30 (10 * 3) rows in the 48 X 1 column vector
	first_30 = X_and_theta[:num_movies * num_features]
	# Reshape this column vector into a 10 X 3 matrix
	X = first_30.reshape((num_features, num_movies)).transpose()
	# Get the rest of the 18 the numbers, after the first 30
	last_18 = X_and_theta[num_movies * num_features:]
	# Reshape this column vector into a 6 X 3 matrix
	theta = last_18.reshape(num_features, num_users ).transpose()
	return X, theta


In [19]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply by did_rate because we only want to consider observations for which a rating was given
	difference = X.dot( theta.T ) * did_rate - ratings
	X_grad = difference.dot( theta ) + reg_param * X
	theta_grad = difference.T.dot( X ) + reg_param * theta
	
	# wrap the gradients back into a column vector 
	return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [20]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
	cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
	# '**' means an element-wise power
	regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
	return cost + regularization

In [21]:
from scipy import optimize

In [22]:
reg_param = 30

In [23]:
minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta, 								args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), 								maxiter=100, disp=True, full_output=True ) 
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]
movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)

Optimization terminated successfully.
         Current function value: 140.716667
         Iterations: 10
         Function evaluations: 22
         Gradient evaluations: 22


In [24]:
movie_features

array([[-9.05221577e-08, -2.84962127e-08, -3.71255255e-08],
       [-9.19052318e-08, -7.65001530e-08, -1.13006787e-08],
       [ 2.56495201e-08,  3.98066423e-08,  6.40832113e-08],
       [ 8.66037031e-08,  3.14079709e-08,  1.94718366e-09],
       [ 4.72814367e-08,  1.21385583e-08, -2.01409092e-08],
       [-4.01122043e-08, -2.73755030e-08, -3.94914530e-08],
       [ 7.30603766e-08,  3.27948898e-08, -7.34015784e-09],
       [ 1.28708719e-08, -2.10096267e-08,  3.62873566e-08],
       [ 2.09721223e-08,  3.69521259e-08,  1.35494173e-08],
       [ 4.11751651e-08,  3.98957119e-08,  6.89540928e-08]])

In [25]:
user_prefs

array([[-2.42100560e-08,  7.36900450e-08, -1.96421986e-09],
       [-4.64793560e-08, -9.45131525e-09,  9.43952872e-10],
       [-1.91426664e-08,  1.25487687e-08, -7.63241526e-08],
       [ 2.69226352e-07, -8.41289459e-08,  7.62847139e-08],
       [-1.51840380e-07,  4.00052698e-08, -7.25813058e-08],
       [-1.43379054e-08, -5.00003790e-08,  2.73964358e-08]])

In [26]:
all_predictions = movie_features.dot( user_prefs.T )

In [27]:
all_predictions

array([[ 1.64582005e-16,  4.44169353e-15,  4.20881736e-15,
        -2.48057040e-14,  1.52995393e-14,  1.70561249e-15],
       [-3.39007189e-15,  4.98405573e-15,  1.66184319e-15,
        -1.91695021e-14,  1.17147341e-14,  4.83316684e-15],
       [ 2.18650343e-15, -1.50790677e-15, -4.88257265e-15,
         8.44520529e-15, -6.95340057e-15, -6.02456012e-16],
       [ 2.13949591e-16, -4.32029293e-15, -1.41231158e-15,
         2.08222199e-14, -1.20347840e-14, -2.75878026e-15],
       [-2.10634145e-16, -2.33134814e-15,  7.84469021e-16,
         1.01717611e-14, -5.23177154e-15, -1.83663841e-15],
       [-9.68613442e-16,  2.08584586e-15,  3.43847737e-15,
        -1.15087844e-14,  7.86182920e-15,  8.61985462e-16],
       [ 6.62278778e-16, -3.71268285e-15, -4.26803604e-16,
         1.63508373e-14, -9.24878872e-15, -2.88838385e-15],
       [-1.93108121e-15, -3.65407677e-16, -3.27962949e-15,
         8.00086625e-15, -5.42859760e-15,  1.86009219e-15],
       [ 2.18865353e-15, -1.31122692e-15, -9.719

In [28]:
predictions_for_me = all_predictions[:, 1:2] + ratings_mean


In [29]:
predictions_for_me

array([[6.5       ],
       [6.6       ],
       [8.5       ],
       [6.6       ],
       [5.75      ],
       [4.6       ],
       [3.75      ],
       [4.66666667],
       [6.        ],
       [4.5       ]])

In [30]:
my_ratings

array([[8.],
       [0.],
       [0.],
       [0.],
       [7.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.]])